config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/contact' => 'pages#contact'
  
  resources :users, :only => [:index, :new, :create]
  resources :items
  resources :orders
  resources :categories


  # Login Sessions
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord 
  belongs_to :user, :optional => true
  belongs_to :category, :optional => true
  has_and_belongs_to_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user, :optional => true
    has_and_belongs_to_many :items
end

app/models/user.rb
class User < ApplicationRecord 
    has_many :orders
    has_many :items
    has_many :categories, :through => :items
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? 
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to login_path unless (@current_user.present? && @current_user.admin?)
  end       
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
    @items = Item.all.where(category_id: params[:id] )
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    @category.save

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @categories = Category.all
  end


  def show
    @item = Item.find params[:id]
  end


  def new
    @item= Item.new
  end

  def create
    item = Item.new item_params
     if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      item.image = req["public_id"]
      item.save
    end
    redirect_to items_path
  end


  def edit
    @item = Item.find params[:id]
  end

  def update
    item = Item.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      item.image = req["public_id"]
    end
    item.update_attributes item_params
    item.save
    redirect_to items_path
  end

  def destroy
    @item = Item.find params[:id]
    @item.destroy
    redirect_to items_path
  end
  private

  def item_params
    params.require(:item).permit(:name, :price, :brand, :description, :images)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 def index 
    @orders = Order.all
 end
    
    
    
    def new
    @order = Order.new

  end

   
  
  def create
    item = Item.find params[:item_id]
    
    # @current_order.items << item

    redirect_to orders_path
  end




  def destroy
    item = Item.find params[:id]
    item.destroy

    redirect_to orders_path
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @items = Item.all
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
def new
  end

  def create
    user = User.find_by :email => params[:email]

if !user.present?
      redirect_to new_user_path 
else
  if user.present? && user.authenticate(params[:password])
      if user.admin == true
        session[:user_id] = user.id
        redirect_to items_path
      else
        session[:user_id] = user.id
      redirect_to root_path # match  
      end
    else
      flash[:error_message] = "Invalid email or password"
      redirect_to login_path # no match, try again
    end
  end
end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :check_for_admin, :only => [:index]
  def index
    @users = User.all
  end
  

  def show
    @user = User.find params[:id]
    @item = Item.all
    @order = Order.all
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new user_params

    if @user.save # returns truthy on success
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :mobole, :street, :suburb, :city, :country, :postcode, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<br>
<% if  @current_user.present? && @current_user.admin == true %>
  <% @categories.each do |category| %>
    <%= link_to category.name.upcase, category_path(category.id), :class => "btn btn-secondary btn-lg"%>
    <br>
    <br>
  <% end %>
  <p><%= link_to 'Add New Category', new_category_path, :class => "btn btn-primary"%></p>
<% else %>
  <% @categories.each do |category| %>
    <h4>
      <%= link_to category.name.upcase, category_path(category.id), :class => "text-muted"%>
    </h4>
    <br>
  <% end %>
<% end %>

app/views/categories/new.html.erb
<h3 class="text-muted">Add a Categories</h3>
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>
  <%= f.submit "Add Category" %>
<% end %>

app/views/categories/show.html.erb
<br>
<h3 class = "text-muted"><%= @category.name.upcase%></h3>
<div class="container">
  <div class='row'>
    <% @items.each do |item| %>
      <div class="col-md-4 item-box">
        <% if item.image.present? %>
          <%= link_to item_path(item) do %>
            <% if item.image.start_with?('https') %>
              <%= image_tag item.image, :class => "item-index" %>
            <% else %>
              <%= cl_image_tag item.image, :class => "item-index" %>
            <% end %>
          <% end %>
        <% end %>
        <div class="row justify-content-center row-eq-height">
          <h4><%=  link_to item.name, item_path(item), :class => "text-muted" %></h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for(@item, :html => {:multipart =>true}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :brand %>
    <%= f.text_field :brand, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, :require => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, :required => true, :class => 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label "Image of item: " %>
    <%= f.cl_image_upload :image, :required => true, :class => 'form-control' %>
  </div class="form-group">
  <%= f.submit "Add" %>
</div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1 class="text-muted">Edit Item</h1>
  <%= render partial: "form" %>
</div>

app/views/items/index.html.erb
<!-- loops through all the  -->
<%# admin page view %>
<% if @current_user.present? && @current_user.admin == true %>
  <% @items.each do |item| %>
    <h4><%=  link_to item.name, item_path(item), :class => "btn btn-secondary btn-lg" %></h4>
    <%= link_to 'Edit Item', edit_item_path(item), :class => "btn btn-outline-secondary" %>
    <%= link_to 'Remove Item', item_path(item.id), :class => "btn btn-danger", :method => 'delete', :data => {:confirm => 'Are you sure you want to remove this item?'}%>
    <br>
    <br>
    <br>
  <% end %>
  <%= link_to 'ADD NEW ITEM', new_item_path, :class => "btn btn-primary"%>
  <%# user page view %>
<% else %>
  <div class="container">
    <div class='row'>
      <% @items.each do |item| %>
        <div class="col-md-4 item-box">
          <% if item.image.present? %>
            <%= link_to item_path(item) do %>
              <% if item.image.start_with?('https') %>
                <%= image_tag item.image, :class => "item-index" %>
              <% else %>
                <%= cl_image_tag item.image, :class => "item-index" %>
              <% end %>
            <% end %>
          <% end %>
          <div class="row justify-content-center row-eq-height">
            <h4><%=  link_to item.name, item_path(item), :class => "text-muted" %></h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<div class="container">
  <h2>Add an Item</h2>
  <%= render partial: "form" %>
</div>

app/views/items/show.html.erb
<h3 class="text-muted"><%= @item.name %></h3>
<%# admin page view %>
<% if @current_user.present? && @current_user.admin == true %>
  <p><%= link_to 'Edit Item', edit_item_path %></p>
  <p><%= link_to 'Remove Item', item_path(@item.id), :method => 'delete', :data => {:confirm => 'Are you sure you want to remove this item?'}%></p>
  <div>
    <% if @item.image.present? %>
      <% if @item.image.start_with?('https') %>
        <p><%= image_tag @item.image %></p>
      <% else %>
        <p><%= cl_image_tag @item.image %></p>
      <% end %>
      <h5>Price</h5>
      <p><%= number_to_currency @item.price %></p>
      <h5>Brand</h5>
      <p><%= @item.brand %></p>
      <h5>Description</h5>
      <p><%= @item.description %></p>
    <% end %>
  </div>
  <%# user page view %>
<% else %>
  <div>
    <% if @item.image.present? %>
      <% if @item.image.start_with?('https') %>
        <p><%= image_tag @item.image, :class => "item-show"%></p>
      <% else %>
        <p><%= cl_image_tag @item.image, :class => "item-show" %></p>
      <% end %>
    <% end %>
    <h5>Price</h5>
    <p><%= number_to_currency @item.price %></p>
    <h5>Brand</h5>
    <p><%= @item.brand %></p>
    <h5>Description</h5>
    <p><%= @item.description %></p>
    <%= button_to 'add to cart', orders_path(:item_id => @item.id), :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheParks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= cloudinary_js_config %>
  </head>
  <body>
    <div class="container">
      <div class="p-3 mb-2 bg-dark text-white">
        <p class="text-center">Free express shipping on all orders $200AUD+ | DHL available for all international orders</p>
      </div>
      <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: rgba(176,196,222,0.1);">
        <a class="navbar-brand" href="<%= root_path %>">
          <i class="fas fa-camera"></i>
          TheParks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <%# nav home %>
            <li class="nav-item ">
              <a class="nav-link" href="<%= root_path %>">Home</a>
            </li>
            <%# nav items %>
            <li class="nav-item">
              <a class="nav-link" href="<%= items_path %>">Items</a>
            </li>
            <%# nav categories %>
            <li class="nav-item">
              <a class="nav-link" href="<%= categories_path %>">Categories</a>
            </li>
            <%# nav contact %>
            <li class="nav-item">
              <a class="nav-link" href="<%= contact_path %>">Contact Us</a>
            </li>
            <% if @current_user.present? %>
              <%# admin page view %>
              <%# nav Logout %>
              <% if  @current_user.admin == true %>
                <%# nav User List %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= users_path %>">User List</a>
                </li>
                <%# nav Logout %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= login_path %>" data-method="delete">Sign Out  <%=  @current_user.username.upcase%></a>
                </li>
              <% else %>
                <%# nav order List %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= orders_path %>">Your Order</a>
                </li>
                <%# nav Logout %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= login_path %>" data-method="delete">Sign Out  <%=  @current_user.username.upcase%></a>
                </li>
              <% end %>
            <%else  %>
              <%# nav Sign Up %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_path %>">Sign UP</a>
              </li>
              <%# nav Sign IN %>
              <li class="nav-item">
                <a class="nav-link" href="<%= login_path %>">Sign IN</a>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <div><%= yield %></div>
    </div>
    <div class="footer-basic">
      <footer>
        <div class="social">
          <a href="https://www.instagram.com/theparkssydney/?hl=en"><i class="icon ion-social-instagram"></i></a>
          <a href="https://github.com/smartnelly"><i class="icon ion-social-github"></i></a>
          <a href="https://twitter.com/Nelly_qiongdai"><i class="icon ion-social-twitter"></i></a>
          <a href="https://www.linkedin.com/in/nelly-dai/"><i class="icon ion-social-linkedin"></i></a></div>
        <p class="copyright">Company Name © 2021</p>
      </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/orders/index.html.erb
<br>
<h1 class="text-muted">No, you ain't got cash, but you got ME, baby!</h1>
<br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/31crA53Dgu0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

app/views/pages/contact.html.erb
<br>
<h3 class="text-muted">Store Address:</h3>
<p class="text-muted">Shop 21, 501 George St, Level 9, Regent's Place Shopping Centre Lower Ground Level, Sydney NSW 2000</p>
<h3 class="text-muted">Opening Hours:</h3>
<p class="text-muted">Mon 12 - 6.30pm</p>
<p class="text-muted">Tue 12 - 6.30pm</p>
<p class="text-muted">Wed 12 - 6.30pm</p>
<p class="text-muted">Thu 12 - 6.30pm</p>
<p class="text-muted">Fri 12 - 6.30pm</p>
<p class="text-muted">Sat 12 - 6.30pm</p>
<p class="text-muted">Sun 12 - 6.30pm</p>
<h3 class="text-muted">Phone Number:</h3>
<p class="text-muted">0451990523</p>
<h3 class="text-muted">Email:</h3>
<p class="text-muted">accounts@theparks.cn</p>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d26500.35328992937!2d151.21738792019042!3d-33.87563677351492!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe13cdad0c3e7ab96!2sThe%20Parks%20Sydney%20Sneaker%2FFashion%20Store!5e0!3m2!1sen!2sau!4v1619732690648!5m2!1sen!2sau" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

app/views/pages/home.html.erb
<br>
<div>
  <img src="assets/bgi.png"></div>
<br>
<div>
  <h2>THE PARKS SYDNEY</h2>
  <p>Combining, buying and selling. The Parks Sydney specialises in sharing the latest news in fashion. 
    The Parks is Doctor Insole's (TM) sneaker market place. Doctor Insole had visions of creating the most dedicated and professional sneaker platform since 2005. With over 12 years of experience and is the most seasoned sneaker pros from the Australiasia region. 
    The Park's goal is to establish a unique and dedicated platform to share with their fans including the latest news and trends in the sneaker industry. Not only is the Parks a market place where you can obtain your most wanted sneakers, but it is also a social space where all sneakerheads, seasoned or young can come together and share their stories. 
    We are not just a market place, we integrate fashion with daily living, we are The Parks.</p>
</div>

app/views/session/new.html.erb
<h2 class="text-muted">Log In</h2>
<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Sign In" , :class => "btn btn-primary"%>
  <% if flash[:error_message] %>
    <h2><%= flash[:error_message] %></h2>
  <% end %>
<% end %>

app/views/users/index.html.erb
<h2 class="text-muted">All Users</h2>
<% @users.each do |user| %>
  <h3><%= user.name %></h3>
  <p><%= user.email %></p>
  <p><%= user.mobile %></p>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <h2 class="text-muted">Sign up</h2>
  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg|  %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :required => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, :require => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :required => true, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, :required => true, :class => 'form-control' %>
    </div>
    <div class="form-group"></div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :mobile %>
    <%= f.email_field :mobile, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :suburb %>
    <%= f.email_field :suburb, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.email_field :city, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.email_field :country, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :postcode %>
    <%= f.email_field :postcode, :class => 'form-control' %>
  </div>
  <%= f.submit "Sign Up", :class => "btn btn-primary"%>
<% end %>
</div>